### ISSUE TITLE
any readme/makefile

### ISSUE THREAD

**Issue by Dsm0** [casey/blaster#1]
I get the impression this is a small personal project, but I'd like to experiment with it a little bit.

Do you think you could add a quick Readme and/or Makefile regarding how to build it?

**Comment by casey** [comment]
Absolutely! I just added a basic readme with a description and some pointers. It uses the [tup](http://gittup.org/tup/) build system.

I'm also happy to answer any questions you might have. It's definitely not particularly comprehensible.
